### ISSUE TITLE
pngcopy

### ISSUE THREAD

**Issue by ZGainsforth** [jcsalterego/pngpaste#10]
Now if only I could do this:

pngpaste - | convert - -resize 50% - | pngcopy

**Comment by jcsalterego** [comment]
Interesting idea; what is your actual use case for copying a PNG, resizing it and copying it back into the clipboard? Where does it end up?

**Comment by ZGainsforth** [comment]
I am grabbing screen captures on a retina display.  *Sometimes* but not always, I want the resolution halved, and I do this a lot so I don’t want to screen cap to a file, and have to worry about cleaning up trash.  One simple solution is to make a simple terminal command which allows me to down sample the clipboard.

like this:

[Cmd-shift-4-space] to copy a window to the pasteboard
run terminal command
[Cmd-v] pastes the down sampled image in keynote (usually).

**Comment by jcsalterego** [comment]
This does make me wonder if there's something buried in the OS X API that allows for saving different resolutions. Otherwise, `pngcopy` would be a whole new thing and expand the scope of `pngpaste` considerably.

**Comment by ZGainsforth** [comment]
Incidentally, I've been doing the following in iTerm2:

pngpaste - | convert - -interpolate nearest -filter point -sample 50% - | imgcat

And then I just copy the image out of the terminal.  But it would be nice to replace that last command with pngcopy.  ;-)

**Comment by jcsalterego** [comment]
> pngpaste - | convert - -interpolate nearest -filter point -sample 50% - | imgcat

Ahh, nice.

**Comment by gibfahn** [comment]
>Otherwise, pngcopy would be a whole new thing and expand the scope of pngpaste considerably.

Looks like someone has raised a PR for it! https://github.com/jcsalterego/pngpaste/pull/15

Assuming it works, it'd be great to have this, for me at least it makes sense to have `pngcopy` and `pngpaste` to match `pbcopy` and `pbpaste`.

**Comment by jcsalterego** [comment]
Thanks - I need to revisit things here and merge all the good code and ideas people have contributed.

**Comment by manueliglesias** [comment]
Just leaving my useless +1 in here 😅

I would love to see #15 merged and eventually make its way to `brew`

**Comment by jcsalterego** [comment]
Sorry all, #15 has been closed and I've recommended the author make `pngutils` and fork pngpaste.
