### ISSUE TITLE
State that it's for MacOS in README and description

### ISSUE THREAD

**Issue by dandavison** [jcsalterego/pngpaste#18]
Thanks for this project, it's fantastic to have this functionality.

I'd like to suggest changing the README and repo description to say

```
Paste PNG into files on MacOS, much like pbpaste does for text.
```

Currently the only clue that it's MacOS only is the apple.stackexchange link.

**Comment by jcsalterego** [comment]
Done in master - thanks! https://github.com/jcsalterego/pngpaste/commit/7435942da8b1b5e598cb0996be5633785ffb2ea4
