### ISSUE TITLE
Allow raw binary dump

### ISSUE THREAD

**Issue by brunosaboia** [jcsalterego/pngpaste#21]
Hello,

Thanks for the work with pngpaste.

I would like to have a flag (possible values are, for example, `--raw` and `--binary` — you might come with something better) that would allow pngpaste to behave like `pbpaste`.

That way, I can pipe the raw content to another process, such as `curl`, and upload it directly from memory, without having to create a temp file for that.

Is this something you could do, or should I educate myself with the source and create a PR?

Thanks.

**Comment by win93** [comment]
If you run `pngpaste -h` you will see that this is already supported by this tool. you can do something like `pngpaste - | curl ...` to upload without requiring a temporary file.

**Comment by brunosaboia** [comment]
Thanks, @win93
