### ISSUE TITLE
Error: "261:313: execution error: sh: /us/local bin/pngpaste: No such file or directory (127)"

### ISSUE THREAD

**Issue by tristanotto** [jcsalterego/pngpaste#23]
I’ve tried to set this up with Automator but I’m always getting this error when trying to paste the image.

<img width="259" alt="image" src="https://github.com/jcsalterego/pngpaste/assets/63663187/474350ef-81ee-4c7a-a7c4-d2ea3385f496">

**Comment by jcsalterego** [comment]
Can you run `which pngpaste`? And how are you setting up Automator?

**Comment by tristanotto** [comment]
Returns: /opt/homebrew/bin/pngpaste

<img width="883" alt="image" src="https://github.com/jcsalterego/pngpaste/assets/63663187/541499de-7dae-43f0-9a09-8114e3653ad9">

**Comment by jcsalterego** [comment]
Oh! Try replacing `/usr/local/bin/pngpaste` with `/opt/homebrew/bin/pngpaste` in the Automator Run Shell Script step there.

**Comment by tristanotto** [comment]
> Oh! Try replacing `/usr/local/bin/pngpaste` with `/opt/homebrew/bin/pngpaste` in the Automator Run Shell Script step there.

fixed it! awesome, thank you!
