### ISSUE TITLE
Newer tags with lower version numbers

### ISSUE THREAD

**Issue by ilovezfs** [jcsalterego/pngpaste#6]
Why are there newer tags with lower version numbers than the older tags?

Is this software still being maintained?

**Comment by jcsalterego** [comment]
> Why are there newer tags with lower version numbers than the older tags?

That's... a good question.

> Is this software still being maintained?

Only as far as responding to issues and bug fixes.

Also, ZFS is great.

**Comment by jcsalterego** [comment]
Since homebrew is already bound to 0.2.1, I've gotten rid of the confusing 1.0.0 and 1.0.1 tags. Thanks for noticing!

**Comment by ilovezfs** [comment]
Thanks @jcsalterego 

The reason I noticed this was because `brew livecheck` flagged it automatically for upgrade, but then I saw that it was actually an older tag. Now if `brew livecheck` flags it again, we'll know it's a "real" upgrade. Thanks for taking care of this.
